# The whistle: a true sine whose pitch follows a short melody, gliding
# between notes (portamento) with a steady vibrato. One phrase = one tile.
function sm(t) { if (t < 0) t = 0; if (t > 1) t = 1; return t * t * (3 - 2 * t) }
function semis(x,   i, s, t) {
  for (i = 1; i <= n; i++) if (x < b[i]) break
  if (i > n) i = n
  s = S[i]
  if (i < n && x > b[i] - G / 2) { t = (x - (b[i] - G / 2)) / G; s = S[i] + (S[i + 1] - S[i]) * sm(t) }
  if (i > 1 && x < b[i - 1] + G / 2) { t = (x - (b[i - 1] - G / 2)) / G; s = S[i - 1] + (S[i] - S[i - 1]) * sm(t) }
  return s
}
function freq(x) { return F0 * 2 ^ (semis(x) / 12) * (1 + V * sin(2 * PI * x / VP)) }
BEGIN {
  PI = 3.141592653589793
  n = split("0 5 7 12 10 7 0 -5 0", S, " ")
  split("70 60 80 60 60 60 110 60 80", D, " ")
  b[0] = 0; for (i = 1; i <= n; i++) b[i] = b[i - 1] + D[i]
  W = b[n]; G = 26; F0 = 1 / 28; V = 0.05; VP = 32; A = 5.5; MID = 8; H = 16; DX = 0.25
  # Total cycles over the tile; trim the pitch so the phrase closes on a whole cycle.
  P = 0; for (x = 0; x < W; x += DX) P += freq(x + DX / 2) * DX
  k = int(P + 0.5) / P
  ph = 0; d = sprintf("M0 %.2f", MID)
  for (x = 0; x < W; x += DX) {
    ph += k * freq(x + DX / 2) * DX
    xx = x + DX
    if (xx == int(xx)) d = d sprintf(" L%d %.2f", xx, MID - A * sin(2 * PI * ph))
  }
  printf "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\">\n", W, H, W, H
  printf "  <!-- The whistle (G-funk lead): a true sine following a nine-note phrase\n"
  printf "       (0 +5 +7 +12 +10 +7 0 -5 0 semitones) with portamento glides and a\n"
  printf "       5%% vibrato; %d cycles per %dpx tile, seamless. Generated by\n", int(P + 0.5), W
  printf "       site/img/whistle.awk (awk -f site/img/whistle.awk > site/img/whistle.svg). -->\n"
  printf "  <path d=\"%s\" fill=\"none\" stroke=\"#e9b94e\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n</svg>\n", d
  printf "cycles %.3f -> %d (pitch x%.4f)\n", P, int(P + 0.5), k > "/dev/stderr"
}
