# The whistle (the G-funk lead): a true sine whose pitch follows a short
# minor-pentatonic phrase, gliding between notes (portamento). Held notes
# get a delayed, shallow vibrato, the way a player holds a note and then lets
# it sing. One phrase = one seamless tile.
#   awk -f site/img/whistle.awk > site/img/whistle.svg
# The real thing runs ~1,000 cycles a note; a drawing can't, so the phrase is
# squeezed to a few cycles a note. Vibrato is kept true to life instead:
# ~2.5% deep, slower than the tone (a wobble every ~2.5 cycles), late onset.
function sm(t) { if (t < 0) t = 0; if (t > 1) t = 1; return t * t * (3 - 2 * t) }
function note(x,   i) { for (i = 1; i <= n; i++) if (x < b[i]) return i; return n }
function semis(x,   i, s, t) {
  i = note(x); s = S[i]
  if (i < n && x > b[i] - G / 2) { t = (x - (b[i] - G / 2)) / G; s = S[i] + (S[i + 1] - S[i]) * sm(t) }
  if (i > 1 && x < b[i - 1] + G / 2) { t = (x - (b[i - 1] - G / 2)) / G; s = S[i - 1] + (S[i] - S[i - 1]) * sm(t) }
  return s
}
# Vibrato on held notes only: it starts a third of the way in, eases in over
# RAMP px, and eases out before the glide to the next note.
function vib(x,   i, on, off, e) {
  i = note(x)
  if (D[i] < HOLD) return 0
  on = b[i - 1] + D[i] / 3; off = b[i] - G / 2
  e = sm((x - on) / RAMP) * (1 - sm((x - (off - RAMP / 2)) / (RAMP / 2)))
  return V * e * sin(2 * PI * (x - on) / VP)
}
function freq(x) { return F0 * 2 ^ (semis(x) / 12) * (1 + vib(x)) }
BEGIN {
  PI = 3.141592653589793
  n = split("0 5 7 12 10 7 0 -5 0", S, " ")
  split("100 70 90 170 60 70 180 70 150", D, " ")
  b[0] = 0; for (i = 1; i <= n; i++) b[i] = b[i - 1] + D[i]
  W = b[n]; G = 26; F0 = 1 / 28; A = 5.5; MID = 8; H = 16; DX = 0.25
  V = 0.025; VP = 64; HOLD = 150; RAMP = 40
  # Total cycles over the tile; trim the pitch so the phrase closes on a whole cycle.
  P = 0; for (x = 0; x < W; x += DX) P += freq(x + DX / 2) * DX
  k = int(P + 0.5) / P
  ph = 0; d = sprintf("M0 %.2f", MID)
  for (x = 0; x < W; x += DX) {
    ph += k * freq(x + DX / 2) * DX
    xx = x + DX
    if (xx == int(xx)) d = d sprintf(" L%d %.2f", xx, MID - A * sin(2 * PI * ph))
  }
  printf "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\">\n", W, H, W, H
  printf "  <!-- The whistle (G-funk lead): a true sine following a nine-note phrase\n"
  printf "       (0 +5 +7 +12 +10 +7 0 -5 0 semitones) with portamento glides and a\n"
  printf "       delayed 2.5%% vibrato on held notes; %d cycles per %dpx tile, seamless.\n", int(P + 0.5), W
  printf "       Generated by site/img/whistle.awk. -->\n"
  printf "  <path d=\"%s\" fill=\"none\" stroke=\"#e9b94e\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n</svg>\n", d
  printf "cycles %.3f -> %d (pitch x%.4f), tile %dpx\n", P, int(P + 0.5), k, W > "/dev/stderr"
}
